---
# Source: metallb/templates/l2-advertisement.yaml
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ipAddressPools:
  - default
