addressPool:
  name: default
  addresses: 10.172.242.242-10.172.242.254
metallb:
  controller:
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 20m
        memory: 96Mi
  speaker:
    resources:
      limits:
        cpu: 200m
        memory: 96Mi
      requests:
        cpu: 20m
        memory: 80Mi
    frr:
      resources:
        limits:
          cpu: 200m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
    reloader:
      resources:
        limits:
          cpu: 100m
          memory: 32Mi
        requests:
          cpu: 5m
          memory: 8Mi
    frrMetrics:
      resources:
        limits:
          cpu: 200m
          memory: 64Mi
        requests:
          cpu: 20m
          memory: 16Mi
