{{- if .Capabilities.APIVersions.Has "metallb.io/v1beta1" -}}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.addressPool.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ipAddressPools:
  - {{ .Values.addressPool.name }}
{{- end -}}
